export enum ResolutionDecision {
  PENDING = 'PENDING',
  REFUND_CUSTOMER = 'REFUND_CUSTOMER',
  FORCE_PAYOUT = 'FORCE_PAYOUT',
  SPLIT_COST = 'SPLIT_COST',
  ESCALATE_TO_HUMAN = 'ESCALATE_TO_HUMAN'
}
